// Runtime palette-indexing flags, captured from the original game.
//
// A .tc stream carries either direct ARGB4444 pixels or 12-bit palette indices,
// and nothing in the file says which: the engine decides at the call site, by
// which of two loader wrappers it uses (0x100b572c passes 0 -> direct colour,
// 0x100b573c passes 1 -> indexed, palette at obj+0x48). Guessing from pixel
// values gets it wrong on dark textures whose indices happen to look like
// plausible colours -- fog, water2, smallprojectile, seagull_shadow and
// anim/img/black all fooled that heuristic, and the symptom is sprites that
// render blue-green with red always zero.
//
// So these are ground truth instead: the flag the running game passed, logged
// by the EKA2L1 probe in tools/eka2l1/ over several play sessions. 283 assets
// were observed; anything not listed falls back to the heuristic.
//
// This file is generated from tools/tc_paletted.json; see tools/README.md.
#include "game/PaletteFlags.h"

#include <algorithm>
#include <cctype>
#include <cstring>

namespace bb {
namespace {

// Sorted by path (uppercase, forward slashes) for binary search.
struct Flag { const char* Path; bool Indexed; };
constexpr Flag kFlags[] = {
    {"DATA/ANIM/IMG/00-CARIBBEAN-BACKGROUND.TC", false},
    {"DATA/ANIM/IMG/00-CARIBBEAN-FOREGROUND.TC", false},
    {"DATA/ANIM/IMG/00-INTRO-EXTERIOR.TC", false},
    {"DATA/ANIM/IMG/00-INTRO-PAINTINGS-CLOSEUP1.TC", false},
    {"DATA/ANIM/IMG/00-INTRO-PAINTINGS.TC", false},
    {"DATA/ANIM/IMG/00-KNUCKLES-BACKGROUND.TC", false},
    {"DATA/ANIM/IMG/00-MARCEL.TC", false},
    {"DATA/ANIM/IMG/00-PISTOL-BACKGROUND.TC", false},
    {"DATA/ANIM/IMG/00-PISTOL-SHADOW.TC", false},
    {"DATA/ANIM/IMG/00-SILHOUETTE-BACKGROUND.TC", false},
    {"DATA/ANIM/IMG/00-SILHOUETTE-CROGO.TC", false},
    {"DATA/ANIM/IMG/00-SILHOUETTE-HENCHMAN1.TC", false},
    {"DATA/ANIM/IMG/00-SILHOUETTE-HENCHMAN2.TC", false},
    {"DATA/ANIM/IMG/00-WILHELM-TRAPPED-CLOSEUP.TC", false},
    {"DATA/ANIM/IMG/00-WILHELM-TRAPPED.TC", false},
    {"DATA/ANIM/IMG/01-DISCUSSION.TC", false},
    {"DATA/ANIM/IMG/01-DISCUSSION_FIRE.TC", false},
    {"DATA/ANIM/IMG/01-DISCUSSION_MARCEL.TC", false},
    {"DATA/ANIM/IMG/01-MARCEL.TC", false},
    {"DATA/ANIM/IMG/01-MOONLIGHT-BACKGROUND.TC", false},
    {"DATA/ANIM/IMG/01-MOONLIGHT-SHIP.TC", false},
    {"DATA/ANIM/IMG/BLACK.TC", false},
    {"DATA/ANIM/IMG/PIKKULINTU5.TC", false},
    {"DATA/ANIM/SUB-BG.TC", false},
    {"DATA/ANIM/SUB-BGA.TC", false},
    {"DATA/ANIM/SUB-NAME-END.TC", false},
    {"DATA/ANIM/SUB-NAME-SECONDARY.TC", false},
    {"DATA/ANIM/SUB-NAME-START.TC", false},
    {"DATA/ANIM/SUB-NAME-TOP.TC", false},
    {"DATA/ANIM/SUB-NAME.TC", false},
    {"DATA/BATTLE/GFX/BUILDINGS.TC", true},
    {"DATA/BATTLE/GFX/CANNON-TOWER.TC", true},
    {"DATA/BATTLE/GFX/CANNON.TC", true},
    {"DATA/BATTLE/GFX/CAVALRY-HEAVY.TC", true},
    {"DATA/BATTLE/GFX/CAVALRY-LIGHT.TC", true},
    {"DATA/BATTLE/GFX/DUST.TC", false},
    {"DATA/BATTLE/GFX/GALLEY.TC", true},
    {"DATA/BATTLE/GFX/HIDSU.TC", true},
    {"DATA/BATTLE/GFX/ICON/HEALTH.TC", false},
    {"DATA/BATTLE/GFX/ICON/STATES.TC", false},
    {"DATA/BATTLE/GFX/ICON/TURNTIME_BV.TC", false},
    {"DATA/BATTLE/GFX/MANOWAR.TC", true},
    {"DATA/BATTLE/GFX/MAP/D.TC", false},
    {"DATA/BATTLE/GFX/MAP/DL.TC", false},
    {"DATA/BATTLE/GFX/MAP/DR.TC", false},
    {"DATA/BATTLE/GFX/MAP/L.TC", false},
    {"DATA/BATTLE/GFX/MAP/R.TC", false},
    {"DATA/BATTLE/GFX/MAP/U.TC", false},
    {"DATA/BATTLE/GFX/MAP/UL.TC", false},
    {"DATA/BATTLE/GFX/MAP/UR.TC", false},
    {"DATA/BATTLE/GFX/MORTAR.TC", true},
    {"DATA/BATTLE/GFX/MOTHERSHIP.TC", true},
    {"DATA/BATTLE/GFX/MUSKETEER.TC", true},
    {"DATA/BATTLE/GFX/NATURE.TC", false},
    {"DATA/BATTLE/GFX/PART/BOOST-FLAME.TC", false},
    {"DATA/BATTLE/GFX/PART/DUST.TC", false},
    {"DATA/BATTLE/GFX/PART/FADE-CLOUD.TC", false},
    {"DATA/BATTLE/GFX/PART/FIREDUSTSMALL.TC", false},
    {"DATA/BATTLE/GFX/PART/SMALL-CLOUD.TC", false},
    {"DATA/BATTLE/GFX/PART/SPARK.TC", false},
    {"DATA/BATTLE/GFX/PART/SUPPLY.TC", false},
    {"DATA/BATTLE/GFX/PART/WAVEDUST.TC", false},
    {"DATA/BATTLE/GFX/PERK/0.TC", false},
    {"DATA/BATTLE/GFX/PISTOLEER.TC", true},
    {"DATA/BATTLE/GFX/ROWING-BOAT.TC", true},
    {"DATA/BATTLE/GFX/SCORCH-CANNON.TC", true},
    {"DATA/BATTLE/GFX/SCOUT.TC", true},
    {"DATA/BATTLE/GFX/SLOOP.TC", true},
    {"DATA/BATTLE/GFX/SWORDSMEN.TC", true},
    {"DATA/BATTLE/GFX/TILES/BRIDGE.TC", false},
    {"DATA/BATTLE/GFX/TILES/FOG.TC", false},
    {"DATA/BATTLE/GFX/TILES/GRASS_0.TC", false},
    {"DATA/BATTLE/GFX/TILES/GRASS_1.TC", false},
    {"DATA/BATTLE/GFX/TILES/MIST.TC", false},
    {"DATA/BATTLE/GFX/TILES/RANGE_ATT.TC", false},
    {"DATA/BATTLE/GFX/TILES/RANGE_MOV.TC", false},
    {"DATA/BATTLE/GFX/TILES/ROAD_0.TC", false},
    {"DATA/BATTLE/GFX/TILES/WALL_0.TC", false},
    {"DATA/BATTLE/GFX/TILES/WALL_1.TC", false},
    {"DATA/BATTLE/GFX/TILES/WATER.TC", false},
    {"DATA/BATTLE/GFX/TILES/WATER2.TC", false},
    {"DATA/BATTLE/GFX/TILES/WATER_0.TC", false},
    {"DATA/BATTLE/GFX/TRANSPORT-HEAVY.TC", true},
    {"DATA/BATTLE/GFX/WAGON.TC", true},
    {"DATA/CURSOR/ATTACK.TC", false},
    {"DATA/CURSOR/ATTACK_CURSOR.TC", false},
    {"DATA/CURSOR/BUILD.TC", false},
    {"DATA/CURSOR/CANCEL.TC", false},
    {"DATA/CURSOR/CAPTURE.TC", false},
    {"DATA/CURSOR/CURSOR.TC", false},
    {"DATA/CURSOR/INVALID.TC", false},
    {"DATA/CURSOR/JOIN.TC", false},
    {"DATA/CURSOR/LOAD.TC", false},
    {"DATA/CURSOR/SELECTION.TC", false},
    {"DATA/CURSOR/UNLOAD.TC", false},
    {"DATA/FIGHT/GFX/128.TC", false},
    {"DATA/FIGHT/GFX/BLANK_PERK.TC", false},
    {"DATA/FIGHT/GFX/FA_UI_LEFT.TC", false},
    {"DATA/FIGHT/GFX/FA_UI_NAME.TC", false},
    {"DATA/FIGHT/GFX/FA_UI_RIGHT.TC", false},
    {"DATA/FIGHT/GFX/MIST-LEFT.TC", false},
    {"DATA/FIGHT/GFX/MIST-LEFT2.TC", false},
    {"DATA/FIGHT/GFX/PART/SMALLPROJECTILE.TC", false},
    {"DATA/FIGHT/GFX/TURNTIME_FA.TC", false},
    {"DATA/FIGHT/GFX/UNIT/10-0.TC", true},
    {"DATA/FIGHT/GFX/UNIT/10-1.TC", true},
    {"DATA/FIGHT/GFX/UNIT/11-0.TC", true},
    {"DATA/FIGHT/GFX/UNIT/11-1.TC", true},
    {"DATA/FIGHT/GFX/UNIT/11-4.TC", true},
    {"DATA/FIGHT/GFX/UNIT/11-5.TC", true},
    {"DATA/FONT-BIG.TC", false},
    {"DATA/FONT-SMALL.TC", false},
    {"DATA/ICONS/AD_BAR.TC", false},
    {"DATA/ICONS/AMMO.TC", false},
    {"DATA/ICONS/AMOUNT.TC", false},
    {"DATA/ICONS/BONUS_BAR.TC", false},
    {"DATA/ICONS/CAPTURE.TC", false},
    {"DATA/ICONS/COMBAT_TYPE/CAPTURE.TC", false},
    {"DATA/ICONS/COMBAT_TYPE/CLOSE.TC", false},
    {"DATA/ICONS/COMBAT_TYPE/INDIRECT.TC", false},
    {"DATA/ICONS/COMBAT_TYPE/PRODUCTION.TC", false},
    {"DATA/ICONS/COMBAT_TYPE/STATIONARY.TC", false},
    {"DATA/ICONS/COMBAT_TYPE/TRANSPORT.TC", false},
    {"DATA/ICONS/DEFENSE.TC", false},
    {"DATA/ICONS/FLAGS-MED.TC", false},
    {"DATA/ICONS/FLAGS-SMALL.TC", false},
    {"DATA/ICONS/FLAGS.TC", false},
    {"DATA/ICONS/HEALTH.TC", false},
    {"DATA/ICONS/MARKER.TC", false},
    {"DATA/ICONS/MONEY.TC", false},
    {"DATA/ICONS/MOVEMENT.TC", false},
    {"DATA/ICONS/MOVEMENT_BONUS.TC", false},
    {"DATA/ICONS/PROP_LARGE.TC", false},
    {"DATA/ICONS/PROP_SMALL.TC", true},
    {"DATA/ICONS/RANGE_CLOSE.TC", false},
    {"DATA/ICONS/RANGE_INDIRECT.TC", false},
    {"DATA/ICONS/RATIONS.TC", false},
    {"DATA/ICONS/TERRAIN_LARGE.TC", false},
    {"DATA/ICONS/TERRAIN_SMALL.TC", false},
    {"DATA/ICONS/UNITS_LARGE/CANNON-TOWER.TC", true},
    {"DATA/ICONS/UNITS_LARGE/CANNON.TC", true},
    {"DATA/ICONS/UNITS_LARGE/CHARIOT.TC", true},
    {"DATA/ICONS/UNITS_LARGE/GALLEY.TC", true},
    {"DATA/ICONS/UNITS_LARGE/HEAVY-CAVALRY.TC", true},
    {"DATA/ICONS/UNITS_LARGE/HIDSU.TC", true},
    {"DATA/ICONS/UNITS_LARGE/HUT.TC", true},
    {"DATA/ICONS/UNITS_LARGE/LIGHT-CAVALRY.TC", true},
    {"DATA/ICONS/UNITS_LARGE/MAN-O-WAR.TC", true},
    {"DATA/ICONS/UNITS_LARGE/MORTAR.TC", true},
    {"DATA/ICONS/UNITS_LARGE/MOTHERSHIP.TC", true},
    {"DATA/ICONS/UNITS_LARGE/MUSKETEER.TC", true},
    {"DATA/ICONS/UNITS_LARGE/PISTOLEER.TC", true},
    {"DATA/ICONS/UNITS_LARGE/ROWING-BOAT.TC", true},
    {"DATA/ICONS/UNITS_LARGE/SCORCH-CANNON.TC", true},
    {"DATA/ICONS/UNITS_LARGE/SCOUT.TC", true},
    {"DATA/ICONS/UNITS_LARGE/SLOOP.TC", true},
    {"DATA/ICONS/UNITS_LARGE/SWORDMEN.TC", true},
    {"DATA/ICONS/UNITS_SMALL/CANNON-TOWER.TC", true},
    {"DATA/ICONS/UNITS_SMALL/CANNON.TC", true},
    {"DATA/ICONS/UNITS_SMALL/CHARIOT.TC", true},
    {"DATA/ICONS/UNITS_SMALL/GALLEY.TC", true},
    {"DATA/ICONS/UNITS_SMALL/HEAVY-CAVALRY.TC", true},
    {"DATA/ICONS/UNITS_SMALL/HIDSU.TC", true},
    {"DATA/ICONS/UNITS_SMALL/HUT.TC", true},
    {"DATA/ICONS/UNITS_SMALL/LIGHT-CAVALRY.TC", true},
    {"DATA/ICONS/UNITS_SMALL/MAN-O-WAR.TC", true},
    {"DATA/ICONS/UNITS_SMALL/MORTAR.TC", true},
    {"DATA/ICONS/UNITS_SMALL/MOTHERSHIP.TC", true},
    {"DATA/ICONS/UNITS_SMALL/MUSKETEER.TC", true},
    {"DATA/ICONS/UNITS_SMALL/PISTOLEER.TC", true},
    {"DATA/ICONS/UNITS_SMALL/ROWING-BOAT.TC", true},
    {"DATA/ICONS/UNITS_SMALL/SCORCH-CANNON.TC", true},
    {"DATA/ICONS/UNITS_SMALL/SCOUT.TC", true},
    {"DATA/ICONS/UNITS_SMALL/SLOOP.TC", true},
    {"DATA/ICONS/UNITS_SMALL/SWORDMEN.TC", true},
    {"DATA/ICONS/UNIT_CLASS/ARTILLERY.TC", false},
    {"DATA/ICONS/UNIT_CLASS/ATTACK.TC", false},
    {"DATA/ICONS/UNIT_CLASS/CANNON_TOWERS.TC", false},
    {"DATA/ICONS/UNIT_CLASS/CAVALRY.TC", false},
    {"DATA/ICONS/UNIT_CLASS/DEFENSE.TC", false},
    {"DATA/ICONS/UNIT_CLASS/INFANTRY.TC", false},
    {"DATA/ICONS/UNIT_CLASS/LARGE_SHIPS.TC", false},
    {"DATA/ICONS/UNIT_CLASS/SMALL_SEA.TC", false},
    {"DATA/ICONS/UNIT_TYPE/CARRIAGE.TC", false},
    {"DATA/ICONS/UNIT_TYPE/FOOT.TC", false},
    {"DATA/ICONS/UNIT_TYPE/HORSE.TC", false},
    {"DATA/ICONS/UNIT_TYPE/ROWING.TC", false},
    {"DATA/ICONS/UNIT_TYPE/SAILS.TC", false},
    {"DATA/ICONS/VICTORY.TC", false},
    {"DATA/ICONS/VISION.TC", false},
    {"DATA/LOADSCREEN/LOADER.TC", false},
    {"DATA/LOADSCREEN/NOKIA_LOGO_EN.TC", false},
    {"DATA/LOADSCREEN/NOKIA_SPLASH_EN.TC", false},
    {"DATA/LOADSCREEN/SPLASH_ESRB_START.TC", false},
    {"DATA/LOADSCREEN/SPLASH_HS.TC", false},
    {"DATA/LOADSCREEN/SPLASH_OFLC.TC", false},
    {"DATA/LOADSCREEN/SPLASH_RL.TC", false},
    {"DATA/MENU/3ROWS.TC", false},
    {"DATA/MENU/ANGLE_ARROW.TC", false},
    {"DATA/MENU/BOARD.TC", false},
    {"DATA/MENU/BUILDSCROLLDOWN.TC", false},
    {"DATA/MENU/BUILDSCROLLUP.TC", false},
    {"DATA/MENU/BUILD_BG.TC", false},
    {"DATA/MENU/BUILD_ITEM_BG.TC", false},
    {"DATA/MENU/BV_ARROW.TC", false},
    {"DATA/MENU/BV_BOARD.TC", false},
    {"DATA/MENU/BV_PROP_BG.TC", false},
    {"DATA/MENU/BV_SMALL_BOARD.TC", false},
    {"DATA/MENU/BV_SQUARE.TC", false},
    {"DATA/MENU/BV_TEXT_BG.TC", false},
    {"DATA/MENU/CARGO_ICON_BG.TC", false},
    {"DATA/MENU/COMMANDER_BG.TC", false},
    {"DATA/MENU/FISH.TC", false},
    {"DATA/MENU/FULLBOARD.TC", false},
    {"DATA/MENU/HEADER_BG.TC", false},
    {"DATA/MENU/HIGH_SEIZE.TC", false},
    {"DATA/MENU/INFO_BG.TC", false},
    {"DATA/MENU/INPUT_BG.TC", false},
    {"DATA/MENU/LEFT_SB.TC", false},
    {"DATA/MENU/NAME_BOARD.TC", false},
    {"DATA/MENU/PERKMETER.TC", false},
    {"DATA/MENU/PERKPOINTER.TC", false},
    {"DATA/MENU/PERK_BOARD.TC", false},
    {"DATA/MENU/PLANK-26-PLAYER.TC", false},
    {"DATA/MENU/PLANK-27-PLAYERBIG.TC", false},
    {"DATA/MENU/PLANK-28-VERSUS.TC", false},
    {"DATA/MENU/POINTER.TC", false},
    {"DATA/MENU/RIGHT_SB.TC", false},
    {"DATA/MENU/ROUTEARROW.TC", false},
    {"DATA/MENU/SCROLLDOWN.TC", false},
    {"DATA/MENU/SCROLLUP.TC", false},
    {"DATA/MENU/SCROLL_BG.TC", false},
    {"DATA/MENU/SELECT_BIG.TC", false},
    {"DATA/MENU/SELECT_NAME.TC", false},
    {"DATA/MENU/SELECT_SMALL.TC", false},
    {"DATA/MENU/SHELL_BOARD.TC", false},
    {"DATA/MENU/STATS_BG.TC", false},
    {"DATA/MENU/STATUS_BG.TC", false},
    {"DATA/MENU/SUBTOPIC.TC", false},
    {"DATA/MENU/SUB_ITEM.TC", false},
    {"DATA/MENU/SUB_PERK.TC", false},
    {"DATA/MENU/SWORD.TC", false},
    {"DATA/MENU/TERRAIN_BG.TC", false},
    {"DATA/MENU/VOLUME.TC", false},
    {"DATA/MENU/VOLUME_TAB.TC", false},
    {"DATA/MENU/WATER128.TC", false},
    {"DATA/TRAVEL/256.TC", false},
    {"DATA/TRAVEL/GFX/ADESTINATION.TC", false},
    {"DATA/TRAVEL/GFX/AMISSION.TC", false},
    {"DATA/TRAVEL/GFX/AMOVE-TO.TC", false},
    {"DATA/TRAVEL/GFX/HARBOUR-01.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-01.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-02.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-03.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-04.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-05.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-06.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-07.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-08.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-09.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-10.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-11.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-12.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-13.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-14.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-15.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-16.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-17.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-18.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-19.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-20.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-21.TC", false},
    {"DATA/TRAVEL/GFX/ISLAND-22.TC", false},
    {"DATA/TRAVEL/GFX/LOCATIONFLAG.TC", false},
    {"DATA/TRAVEL/GFX/MAP-MARKER-01.TC", false},
    {"DATA/TRAVEL/GFX/MAP-MARKER-02.TC", false},
    {"DATA/TRAVEL/GFX/POINTER-ARROW.TC", false},
    {"DATA/TRAVEL/GFX/ROUTE.TC", false},
    {"DATA/TRAVEL/GFX/SEAGULL.TC", false},
    {"DATA/TRAVEL/GFX/SEAGULL_SHADOW.TC", false},
    {"DATA/TRAVEL/GFX/SHIP-REFL.TC", false},
    {"DATA/TRAVEL/GFX/SHIP.TC", false},
    {"DATA/TRAVEL/GFX/WATER.TC", false},
};

}  // namespace

std::optional<bool> RuntimePaletted(const std::string& gamePath) {
    // Canonical form: uppercase, forward slashes, "DATA/" prefix -- the same
    // normalisation the pak name hash uses.
    std::string key;
    key.reserve(gamePath.size() + 5);
    for (char c : gamePath)
        key.push_back(c == '\\' ? '/' : static_cast<char>(std::toupper(
            static_cast<unsigned char>(c))));
    if (key.rfind("DATA/", 0) != 0) key.insert(0, "DATA/");

    const auto* end = kFlags + sizeof(kFlags) / sizeof(kFlags[0]);
    const auto* it = std::lower_bound(
        kFlags, end, key, [](const Flag& f, const std::string& k) {
            return std::strcmp(f.Path, k.c_str()) < 0;
        });
    if (it == end || key != it->Path) return std::nullopt;
    return it->Indexed;
}

}  // namespace bb
